# Generated by Django 3.0.4 on 2022-10-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectspage_header_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='Показывать шапку'),
        ),
    ]
