# Generated by Django 3.0.4 on 2022-10-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_is_shown'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectspage',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='Показывать шапку'),
        ),
    ]
