# Generated by Django 3.0.4 on 2022-09-26 16:56

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20220222_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='header_font_color',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18, verbose_name='Цвет шрифта в шапке'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='point_font_color',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18, verbose_name='Цвет точки в заголовке'),
        ),
    ]
