# Generated by Django 3.0.4 on 2022-10-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20220926_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='Показывать шапку'),
        ),
    ]
