# Generated by Django 3.0.4 on 2022-10-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contactspage_point_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactspage',
            name='hero_show_block',
            field=models.BooleanField(default=True, verbose_name='Показывать первый экран'),
        ),
    ]
