# Generated by Django 3.0.4 on 2022-10-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contactspage_hero_show_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactspage',
            name='hero_show_block',
        ),
        migrations.AddField(
            model_name='contactspage',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='Показывать шапку'),
        ),
    ]
