# Generated by Django 3.0.4 on 2022-09-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_auto_20220926_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='point_font_color',
        ),
    ]
