# Generated by Django 3.0.4 on 2022-10-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_remove_aboutpage_point_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='is_shown',
            field=models.BooleanField(default=True, verbose_name='Показывать шапку'),
        ),
    ]
