# Generated by Django 3.0.4 on 2022-09-26 16:23

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0008_auto_20220203_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='font_color',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18),
        ),
    ]
