# Generated by Django 3.0.4 on 2022-09-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vars', '0009_siteconfig_font_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='font_color',
        ),
    ]
